import React from 'react';

const Feedback = () => {
  return (
    <div className='grid grid-cols-1 lg:grid-cols-2 gap-4 p-10  bg-slate-500'>
      <header>
        <h1 className='text-red-300 font-bold'>Our Mission</h1>
        <p className='text-white'>Mission and vision statements explain what your business is trying to achieve, what the long-term goal is, and how you’ll get there. Every brand should have a clear idea of their goals and vision to build trust and loyalty, and to attract an audience of like-minded people. When a customer decides they’re going to make a purchase, oftentimes, they want to make sure the company aligns with their values.</p><br />
        <p className='text-white'>These statements matter because they explain what you do, how you do it, and your plans for the future of your company. Consumers and shareholders alike like to make informed decisions. They have options, especially when it comes to what car to buy. These statements help make it clear to both employees and consumers what each organization is about, so they can decide who to align with, work with, and ultimately buy from.</p><br />
        <p className='text-white'>In times of crisis, a mission statement can also help guide a company through a rough patch and help build a better future.</p> <br />
        <p className='text-white'>Now that you know what each statement means and why it matters, let’s explore some examples of some of the top automobile companies in the world.</p>
      </header>
      <section>
        <h1 className='text-gray-300 font-bold'>Popular Questions</h1>
        <div tabindex="0" class="collapse collapse-open border border-base-300 bg-base-100 rounded-box">
          <div class="collapse-title text-xl font-medium">
            Explain The Reason That Why The Tyres Are Always Black In Colour. Is This Phenomena Related To The Heat Conduction?
          </div>
          <div class="collapse-content">
            <p>Tyres colour is black due to the proportion of carbon mixed in it during the vulcanization of the rubber, to make the tyre shear resistant. Without vulcanization tyres won't be able to bear the friction heat and stress of the road. Thus carbon is responsible for giving tyres the prominent black colour. Adding of carbon prevents tyres from rapidly deteriorating because when ozone combines with the ultraviolet light from the sun. It attacks the polymer of the tyre.</p>
          </div>
        </div>
        <div class="collapse m-3">
          <input type="checkbox" class="peer" />
          <div class="collapse-title bg-primary text-primary-content peer-checked:bg-secondary peer-checked:text-secondary-content">
            What Will Happen If Someone Adds Oil To The Fuel Of Four Stroke Bike Engine?
          </div>
          <div class="collapse-content bg-primary text-primary-content peer-checked:bg-secondary peer-checked:text-secondary-content">
            <p>This will result in damaging of the engine faster. Adding oil will lead to the higher wear and tear of the cylinder liner, piston and damage to the piston. It will lead to abnormal combustion and knocking and detonation. Dark smoke and abnormal sounds will be generated by the engine. One should not mix oil with the fuel of four stroke engine.</p>
          </div>
        </div>
        <div class="collapse m-3">
          <input type="checkbox" class="peer" />
          <div class="collapse-title bg-primary text-primary-content peer-checked:bg-secondary peer-checked:text-secondary-content">
            How Will You Differentiate Between Two Stroke Engine And Four Stroke Engine?
          </div>
          <div class="collapse-content bg-primary text-primary-content peer-checked:bg-secondary peer-checked:text-secondary-content">
            <p>In case of two stroke engine, rotation of crank shaft will be power stroke for every two rotations. During compression stroke, fuel will flow towards the crank case(suction) and during power stroke, exhaust will emit the burnt fuel through the transfer ports.

              While in case of four stroke engine, rotation of crank shaft will be power stroke for every four rotation. Moreover, suction compression power and exhaust strokes are separate as there will be inlet and exhaust valves.</p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Feedback;